-- MySQL Script generated by MySQL Workbench
-- Thu Mar 17 11:00:06 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema asl
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ASL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ASL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ASL` ;
USE `ASL` ;

-- -----------------------------------------------------
-- Table `ASL`.`annualGoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASL`.`annualGoal` (
  `year_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `userId` INT(11) NOT NULL COMMENT '',
  `content` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `completed` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `date_added` DATETIME NULL DEFAULT NULL COMMENT '',
  `date_modified` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`year_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ASL`.`dailyGoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASL`.`dailyGoal` (
  `day_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `userId` INT(11) NOT NULL COMMENT '',
  `content` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `completed` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `date_added` DATETIME NULL DEFAULT NULL COMMENT '',
  `date_modified` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`day_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ASL`.`monthlylGoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASL`.`monthlylGoal` (
  `month_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `userId` INT(11) NOT NULL COMMENT '',
  `content` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `completed` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `date_added` DATETIME NULL DEFAULT NULL COMMENT '',
  `date_modified` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`month_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ASL`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASL`.`users` (
  `user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `firstname` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT '' COMMENT '',
  `LastName` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `login` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL DEFAULT '' COMMENT '',
  `password` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `date_added` DATETIME NULL DEFAULT NULL COMMENT '',
  `date_modified` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ASL`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASL`.`note` (
  `note_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `title` VARCHAR(11) NULL DEFAULT NULL COMMENT '',
  `content` TEXT NULL DEFAULT NULL COMMENT '',
  `date_added` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`note_id`)  COMMENT '',
  CONSTRAINT `note_ibfk_1`
    FOREIGN KEY (`note_id`)
    REFERENCES `ASL`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ASL`.`todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASL`.`todo` (
  `todo_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `content` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `completed` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `date_added` DATETIME NULL DEFAULT NULL COMMENT '',
  `date_modified` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`todo_id`)  COMMENT '',
  CONSTRAINT `todo_ibfk_1`
    FOREIGN KEY (`todo_id`)
    REFERENCES `ASL`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ASL`.`weeklyGoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASL`.`weeklyGoal` (
  `week_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `userId` INT(11) NOT NULL COMMENT '',
  `content` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `completed` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `date_added` DATETIME NULL DEFAULT NULL COMMENT '',
  `date_modified` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`week_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
